import {
  IsString,
  IsEmail,
  IsNotEmpty,
  MinLength,
  Matches,
  IsOptional,
  IsBoolean,
  IsObject,
  ValidateNested,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';

export class SignupDto {
  @ApiProperty({ example: 'john.doe@example.com' })
  @IsEmail()
  @IsNotEmpty()
  email: string;

  @ApiProperty({ example: 'John Doe' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'SecurePass123!',
    description:
      'Password must be at least 8 characters with 1 uppercase, 1 lowercase, 1 number',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  @Matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$!%*?&]{8,}$/, {
    message:
      'Password must contain at least 1 uppercase letter, 1 lowercase letter, and 1 number',
  })
  password: string;
}

export class LoginDto {
  @ApiProperty({ example: 'john.doe@example.com' })
  @IsEmail()
  @IsNotEmpty()
  email: string;

  @ApiProperty({ example: 'SecurePass123!' })
  @IsString()
  @IsNotEmpty()
  password: string;
}

export class RefreshTokenDto {
  @ApiProperty({ description: 'The refresh token received during login' })
  @IsString()
  @IsNotEmpty()
  refreshToken: string;
}

export class UpgradeAccountDto {
  @ApiProperty({ example: 'john.doe@example.com' })
  @IsEmail()
  @IsNotEmpty()
  email: string;

  @ApiProperty({ example: 'John Doe' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'SecurePass123!',
    description:
      'Password must be at least 8 characters with 1 uppercase, 1 lowercase, 1 number',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  @Matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$!%*?&]{8,}$/, {
    message:
      'Password must contain at least 1 uppercase letter, 1 lowercase letter, and 1 number',
  })
  password: string;
}

export class LogoutDto {
  @ApiProperty({
    description:
      'Optional: Specific refresh token to logout from. If not provided, logs out from all devices',
    required: false,
  })
  @IsString()
  @IsOptional()
  refreshToken?: string;
}

export class AnonymousSessionDto {
  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Device UUID generated by the client',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, {
    message: 'deviceId must be a valid UUID v4',
  })
  deviceId: string;
}

export class UserMetadataDto {
  @ApiProperty({
    example: false,
    description:
      'Whether user has granted consent for interview recording/analysis',
  })
  @IsBoolean()
  hasGrantedInterviewConsent: boolean;
}

export class UpdateMetadataDto {
  @ApiProperty({
    description: 'User metadata to update',
    type: UserMetadataDto,
  })
  @IsObject()
  @ValidateNested()
  @Type(() => UserMetadataDto)
  metadata: UserMetadataDto;
}

export interface UserResponse {
  id: string;
  email?: string;
  name: string;
  participantIdentity?: string;
  userType: string;
  createdAt?: Date;
  upgradedAt?: Date;
  metadata?: {
    hasGrantedInterviewConsent?: boolean;
  };
}
